config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :boxes do
    member do
      get 'box_items'
      post 'add_scans'
      post 'remove_item'
    end
  end

  get 'boxes/:id/remove_photo', to: 'boxes#remove_photo', as: 'remove_photo_box'
  get 'items/:id/remove_photo', to: 'items#remove_photo', as: 'remove_photo_item'

  get 'items/item_dropdown', to: 'items#item_dropdown', as: 'item_dropdown'
  get 'movements/box_dropdown', to: "movements#box_dropdown", as: "box_dropdown"
  get "university_contacts/contact_dropdown", to: "university_contacts#contact_dropdown", as: "contact_dropdown"
  get "embed_code_universities/university_dropdown", to: "embed_code_universities#university_dropdown", as: "university_dropdown"

  get 'university_contacts/:contact_id/embed_code_universities', to: 'university_contacts#embed_code_universities'
  get 'embed_code_universities/:university_id/university_contacts', to: 'embed_code_universities#university_contacts'

  post 'embed_code_universities/add_contact', to: 'embed_code_universities#add_contact'
  post 'university_contacts/add_university', to: 'university_contacts#add_university'

  post 'embed_code_universities/:contact_id/remove_contact', to: 'embed_code_universities#remove_contact'
  post 'university_contacts/:university_id/remove_university', to: 'university_contacts#remove_university'

  get 'embed_code_universities/new/:contact_id', to: 'embed_code_universities#new'
  get 'university_contacts/new/:university_id', to: 'university_contacts#new'

  delete 'events/remove_university_from_event', to: 'events#remove_university_from_event', as: 'remove_university_from_event'

  get 'events/generate_code', to: 'events#generate_code', as: 'generate_code'
  get 'events/show_code', to: "events#show_code", as: 'show_code'
  get 'embed_codes/:id/get_variables', to: "embed_codes#get_variables", as: 'get_variables'
  post 'events/:events_university_id/add_code', to: "events#add_code", as: "add_code"
  get 'events/edit_event_university', to: "events#edit_event_university", as: "edit_event_university"
  patch 'events/update_events_university', to: "events#update_event_university", as: "update_events_university"

  resources :movements do
    member do
      get 'movement_boxes'
      get 'return'
      post 'add_scans'
      post 'remove_box'
    end
  end
  resources :embed_codes, :embed_code_variables, :events, :software_serials, :softwares, :categories, :products, :items, :users, :locations, :conditions, :university_contacts, :embed_code_universities
  resources :password_resets, only: [:new, :create, :edit, :update]
  # get 'boxes/add_item/:id', to: 'boxes#add_item', as: 'add_item'

  get 'reports', to: 'reports#index', as: 'reports_index'
  get 'reports/boxes_per_movement', to: 'reports#boxes_per_movement_index', as: 'boxes_per_movement_index'
  get 'reports/boxes_per_movement/:id', to: 'reports#boxes_per_movement', as: 'boxes_per_movement'
end

app/models/movement.rb
class Movement < ActiveRecord::Base
	has_paper_trail
	
	has_and_belongs_to_many :boxes
	has_one :return_movement, class_name: "Movement", foreign_key: :return_id
	belongs_to :sent_movement, class_name: "Movement", foreign_key: :return_id
	belongs_to :origin, class_name: "Location", foreign_key: :origin_id
	belongs_to :destination, class_name: "Location", foreign_key: :destination_id
	validates :origin_id, :destination_id, presence: true
	
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user, only: [:return,:new, :create, :edit, :update, :destroy]
  before_action :set_movement, only: [:show, :edit, :update, :destroy, :movement_boxes, :add_scans, :remove_box]
  helper_method :sort_column
  # GET /movements
  # GET /movements.json
  def index
    sc = sort_column
    @q = Movement.ransack(params[:q])
    @sort = sc + " "
    if ["origin_id", "destination_id"].include? sc
      @sort = "locations.country "
    end
    if params[:page]
      cookies[:movements_page] = {
        value: params[:page],
        expires: 1.day.from_now
      }
    end
    @movements = @q.result.includes(:destination, :origin).order(@sort + sort_direction).page(cookies[:movements_page]).per_page(10)
  end

  # GET /movements/1
  # GET /movements/1.json
  def show
  end

  # GET /movements/new
  def new
    @movement = Movement.new
  end

  # GET /movements/1/edit
  def edit
  end

  def movement_boxes
    @boxes = @movement.boxes.order(:box_number)
  end

  def return
    @sent_movement = Movement.find(params[:id])
    @movement = Movement.new
    @movement.is_return = true
    @movement.origin = @sent_movement.destination
    @movement.destination = @sent_movement.origin
    @movement.sent_movement = @sent_movement
    render :new
  end

  def add_scans
    @scans = params.require(:scanned_boxes)
    @boxesRetreived = Box.where(barcode: @scans).order(:barcode)
    @boxesRetreived.each do |box|
      @scans.delete(box.barcode)
    end
    @movement.boxes << @boxesRetreived
    respond_to do |format|
      format.json { render json: [{ notfound: @scans, boxesadded: @boxesRetreived }] }
    end
  end

  def remove_box
    @barcode = params.require(:barcode)
    @box = Box.where(barcode: @barcode)
    @movement.boxes.delete(@box)
    respond_to do |format|
      format.json { render json: [{ confirmation: @box }]}
    end
  end
  # POST /movements
  # POST /movements.json
  def create
    @movement = Movement.new(movement_params)

    respond_to do |format|
      if @movement.save
        if @movement.is_return
          format.html { redirect_to movement_boxes_movement_url(@movement)}
          format.json { render :movement_boxes, status: :created, location: @movement }
        else
          format.html { redirect_to movements_url, notice: 'Movement was successfully created.' }
          format.json { render :show, status: :created, location: @movement }
        end
      else
        format.html { render :new }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movements/1
  # PATCH/PUT /movements/1.json
  def update
    respond_to do |format|
      if @movement.update(movement_params)
        format.html { redirect_to movements_url, notice: 'Movement was successfully updated.' }
        format.json { render :show, status: :ok, location: @movement }
      else
        format.html { render :edit }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movements/1
  # DELETE /movements/1.json
  def destroy
    @movement.destroy
    respond_to do |format|
      format.html { redirect_to movements_url, notice: 'Movement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def box_dropdown
    @movement_id = params.require(:movement_id)
    @boxes = (Box.all.order("box_number") - Movement.find(@movement.id).boxes)
    respond_to do |format|
      format.json { render json: [{ boxes: @boxes }]}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movement
      @movement = Movement.find(params[:id])
    end

    def sort_column
       Movement.column_names.include?(params[:sort]) ? params[:sort] : "shipping_date"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movement_params
      params.require(:movement).permit(:is_return,:origin_id, :destination_id, :return_id, :shipping_date, :arrival_date, :delivery_method)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def admin_user
      redirect_to(movements_url) unless current_user.admin?
    end
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/views/movements/_form.html.erb
<%= form_for @movement, html: { class: "form-horizontal"}, validate: :movement_validators do |f| %>
  <%= f.hidden_field :is_return %>
  <%= f.hidden_field :return_id %>
  <div class="form-group">
    <label class="control-label">Shipping Date</label>
    <%= f.text_field :shipping_date, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label class="control-label">Arrival Date</label>
    <%= f.text_field :arrival_date, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label class="control-label">Destination</label>
    <%= collection_select(:movement, :destination_id, Location.order(country: :asc), :id, :name_with_country, { prompt: "Please select a Destination" }, { class: 'form-control'}) %>
  </div>
  <div class="form-group">
    <label class="control-label">Origin</label>
    <%= collection_select(:movement, :origin_id, Location.order(country: :asc), :id, :name_with_country, { prompt: "Please select an Origin" }, { class: 'form-control'}) %>
  </div>
  <div class="form-group">
    <label class="control-label">Delivery Method</label>
    <%= f.text_field :delivery_method, class: 'form-control' %>
  </div>
  <%= f.submit class: "btn btn-success fullwidthbutton" %>
  <%= link_to 'Back', movements_path, class: "btn btn-warning fullwidthbutton" %>
  
<% end %>

app/views/movements/_movements.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort]%>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= sortable "shipping_date" %></th>
        <th><%= sortable "arrival_date" %></th>
        <th><%= sortable "destination_id", "Destination" %></th>
        <th><%= sortable "origin_id", "Origin" %></th>
        <th><%= sortable "delivery_method" %></th>
        <th>Options</th>
      </tr>
    </thead>

    <tbody>
      <% @movements.each do |movement| %>
        <tr>
        <td><% unless movement.shipping_date.nil? %>
            <%= movement.shipping_date.strftime("%B %e, %Y") %>
          <% end%></td>
          <td><% unless movement.arrival_date.nil? %>
            <%= movement.arrival_date.strftime("%B %e, %Y") %>
          <% end %></td>
          <td><%= movement.destination.present? ? movement.destination.name_with_country : "" %></td>
          <td><%= movement.origin.present? ? movement.origin.name_with_country : "" %></td>
          <td><%= movement.delivery_method %></td>
          <td>
          <% if current_user.admin? %>
            <%= link_to "Boxes", movement_boxes_movement_path(movement) %>
            | <%= link_to 'Edit', edit_movement_path(movement) %>
            | <%= link_to 'Delete', movement, method: :delete %>
            <% unless movement.is_return %>
            | <%= link_to 'Generate Return', return_movement_path(movement) %>
            <% end %>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= will_paginate @movements, renderer: BootstrapPagination::Rails %>

app/views/movements/edit.html.erb
<div class="center-div">
	<%= link_to 'Back', movements_path, class: "btn btn-warning" %>
	<h1 class="text-center">Editing Movement</h1>
	<%= render 'form' %>
	<%= yield(:movement_validators) %>
</div>

app/views/movements/index.html.erb
<h1 class="text-center">Movements</h1>
<%= search_form_for @q, url: movements_path(page: 1), html: { method: :get, class: "form-inline form-main-search", id: "ajax_search"} do |f| %>
	<div class="form-group">
		<%= f.search_field :origin_name_or_origin_country_or_destination_name_or_destination_country_or_delivery_method_cont, class: "form-control" %>
		<%= f.submit "Search", :name => nil, class: "btn btn-primary"%>
	</div>
	<% if current_user.admin? %>
  <%= link_to 'New Movement', new_movement_path, class: "top-index-btn btn btn-success" %>
<% end %>
  <div id="ajax_objects" ><%= render 'movements' %></div>
<% end %>

<% if current_user.admin? %>
  <%= link_to 'New Movement', new_movement_path, class: "btn btn-success" %>
<% end %>

app/views/movements/index.js.erb
$("#ajax_objects").html("<%= escape_javascript(render('movements'))%>")

app/views/movements/movement_boxes.html.erb
<% content_for :extra_js do %>
	<%= javascript_include_tag "barcode_boxes" %>
<% end %>
<h1 class="text-center">Movement from  <%= @movement.origin.name %> to <%= @movement.destination.name %>
<% if @movement.delivery_method.present? %>
 via <%= @movement.delivery_method %>
<% end %>
</h1>
<h3 class="text-center info-title">Add boxes by scanning them or selecting them in the dropdown below</h3>
<div class="center-div movement-info" data-origin="<%= @movement.origin %>" data-destination="<%= @movement.destination %>" data-id="<%= @movement.id %>">
	<%= collection_select(:movement, :box_ids, Box.all.order("box_number") - Movement.find(@movement.id).boxes, :barcode, :box_number_with_barcode, { :include_blank => "Select a Box" }, { class: "form-control box-dropdown top-index-btn"}) %>
	<ul class="list-group main-list">
	<% if @boxes.any? %>
		<% @boxes.each do |box| %>
			<li class="list-group-item list-group-item-info" data-barcode="<%= box.barcode %>"> Box #<%= box.box_number %> (<%= box.barcode %>)<button type="button" class="close remove-box-movement" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button></li>
		<% end %>	
	<% end %>
	</ul>

	<h3 class="text-center hidden not-found-title">The following scans were not found:</h3>
	<ul class="list-group not-found-list">
		
	</ul>

	<h3 class="hidden scan-title text-center">Scanned Boxes</h2>
	<ul class="list-group scanned-boxes">
		
	</ul>
	<button class="hidden loading btn fullwidthbutton btn-info"><span class="fa fa-spinner fa-spin"></span> Loading...</button>
	<a class="hidden add-scan-btn btn btn-primary fullwidthbutton"><span class="fa fa-plus"></span> Add Scanned Boxes</a>
	<%= link_to movements_path, class: "btn btn-warning fullwidthbutton" do %>
		<span class="fa fa-mail-reply"></span> Back 
	<% end %>
</div>

app/views/movements/new.html.erb
<div class="center-div">
  <%= link_to 'Back', movements_path, class: "btn btn-warning" %>
  <h1 class="text-center">New Movement</h1>
  <%= render 'form' %>
  <%= yield(:movement_validators) %>
</div>

app/views/movements/show.html.erb
<div class="center-div">
<div>
	<strong>Destination:</strong>
	<%= @movement.destination.present? ? @movement.destination.name_with_country : "" %>
</div>
<div>
	<strong>Origin:</strong>

	<%= @movement.origin.present? ? @movement.origin.name_with_country : "" %>
</div>
<div>
	<strong>Shipping Date:</strong>
	<%= @movement.shipping_date %>
</div>
<div>
	<strong>Arrival Date:</strong>
	<%= @movement.arrival_date %>
</div>
<div>
	<strong>Delivery Method:</strong>
	<%= @movement.delivery_method %>
</div>
<% if current_user.admin? %>
	<%= link_to 'Edit', edit_movement_path(@movement) %> |
<% end %>
<%= link_to 'Back', movements_path %>
</div>