config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :boxes do
    member do
      get 'box_items'
      post 'add_scans'
      post 'remove_item'
    end
  end

  get 'boxes/:id/remove_photo', to: 'boxes#remove_photo', as: 'remove_photo_box'
  get 'items/:id/remove_photo', to: 'items#remove_photo', as: 'remove_photo_item'

  get 'items/item_dropdown', to: 'items#item_dropdown', as: 'item_dropdown'
  get 'movements/box_dropdown', to: "movements#box_dropdown", as: "box_dropdown"
  get "university_contacts/contact_dropdown", to: "university_contacts#contact_dropdown", as: "contact_dropdown"
  get "embed_code_universities/university_dropdown", to: "embed_code_universities#university_dropdown", as: "university_dropdown"

  get 'university_contacts/:contact_id/embed_code_universities', to: 'university_contacts#embed_code_universities'
  get 'embed_code_universities/:university_id/university_contacts', to: 'embed_code_universities#university_contacts'

  post 'embed_code_universities/add_contact', to: 'embed_code_universities#add_contact'
  post 'university_contacts/add_university', to: 'university_contacts#add_university'

  post 'embed_code_universities/:contact_id/remove_contact', to: 'embed_code_universities#remove_contact'
  post 'university_contacts/:university_id/remove_university', to: 'university_contacts#remove_university'

  get 'embed_code_universities/new/:contact_id', to: 'embed_code_universities#new'
  get 'university_contacts/new/:university_id', to: 'university_contacts#new'

  delete 'events/remove_university_from_event', to: 'events#remove_university_from_event', as: 'remove_university_from_event'

  get 'events/generate_code', to: 'events#generate_code', as: 'generate_code'
  get 'events/show_code', to: "events#show_code", as: 'show_code'
  get 'embed_codes/:id/get_variables', to: "embed_codes#get_variables", as: 'get_variables'
  post 'events/:events_university_id/add_code', to: "events#add_code", as: "add_code"
  get 'events/edit_event_university', to: "events#edit_event_university", as: "edit_event_university"
  patch 'events/update_events_university', to: "events#update_event_university", as: "update_events_university"

  resources :movements do
    member do
      get 'movement_boxes'
      get 'return'
      post 'add_scans'
      post 'remove_box'
    end
  end
  resources :embed_codes, :embed_code_variables, :events, :software_serials, :softwares, :categories, :products, :items, :users, :locations, :conditions, :university_contacts, :embed_code_universities
  resources :password_resets, only: [:new, :create, :edit, :update]
  # get 'boxes/add_item/:id', to: 'boxes#add_item', as: 'add_item'

  get 'reports', to: 'reports#index', as: 'reports_index'
  get 'reports/boxes_per_movement', to: 'reports#boxes_per_movement_index', as: 'boxes_per_movement_index'
  get 'reports/boxes_per_movement/:id', to: 'reports#boxes_per_movement', as: 'boxes_per_movement'
end

app/models/box.rb
class Box < ActiveRecord::Base
	has_paper_trail

	has_and_belongs_to_many :movements
	has_many :items
	has_and_belongs_to_many :conditions
	validates :barcode, :box_number , presence: true
	validates :weight, :height, :width, :depth, numericality: { allow_blank: true}
	validates :box_number, numericality: { only_integer: true }
	validates_uniqueness_of :box_number, case_sensitive: false
	validates_uniqueness_of :barcode, case_sensitive: false
	belongs_to :location

	def box_number_with_barcode
		"##{box_number} (#{barcode})"
	end
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
	before_action :logged_in_user
	before_action :set_box, only: [:show, :edit, :update, :destroy, :box_items, :add_scans, :remove_photo, :remove_item]
	before_action :admin_user, only: [:new, :create, :edit, :update, :destroy, :remove_photo, :remove_item]
	helper_method :sort_column

	# GET /boxes
	# GET /boxes.json
	def index
		sc = sort_column
		@q = Box.ransack(params[:q])
		@sort = sc + " "
		if sc.eql? "location_id"
			@sort = "locations.country "
		end
		if params[:page]
			cookies[:boxes_page] = {
				value: params[:page],
				expires: 1.day.from_now
			}
		end
		@boxes = @q.result.includes(:location).order(@sort + sort_direction).page(cookies[:boxes_page]).per_page(5)
	end

	# GET /boxes/1
	# GET /boxes/1.json
	def show
	end

	# GET /boxes/new
	def new
		@box = Box.new
	end

	# GET /boxes/1/edit
	def edit
	end

	# GET /boxes/1/box_items
	def box_items
		@items = @box.items
	end

	# POST /boxes/1/add_scans
	def add_scans
		@scans = params.require(:scanned_items)
		@itemsRetreived = Item.joins(:product).where(barcode: @scans).order(:barcode)
		@itemsNotInBoxes = @itemsRetreived.select(:id, :barcode, :name).where(box_id: nil)
		@itemsNotInBoxes = @itemsNotInBoxes.map
		@itemsInBoxes = @itemsRetreived.select(:id, :box_id, :box_number, :barcode, :name).joins(:box).where.not(box_id: nil).map
		@oldItemsBoxes = {}
		@itemsInBoxes.each do |item|
			@oldItemsBoxes[item.id] = item.box.box_number
		end
		@itemsRetreived.each do |item|
			item.box = @box
			item.save
			@scans.delete(item.barcode)
		end
		respond_to do |format|
				format.json { render json: [{ notfound: @scans, notinboxitems: @itemsNotInBoxes, movedfrombox: @itemsInBoxes, oldboxesid: @oldItemsBoxes }] }
		end
	end
	# POST /boxes/1/remove_item
	def remove_item
		@barcode = params.require(:barcode)
		@item = Item.where(barcode: @barcode)
		@box.items.delete(@item)
		respond_to do |format|
			format.json { render json: [{ confirmation: @item }]}
		end
	end
	# POST /boxes
	# POST /boxes.json
	def create
		@box = Box.new(box_params)
		if @box.valid? && @box.photo?
			client = kaltura_setup
			entry_id = kaltura_upload(box_params[:barcode], box_params[:photo], client)

			@box.photo = entry_id
		end

		respond_to do |format|
			if @box.save
				format.html { redirect_to @box, notice: 'Box was successfully created.' }
				format.json { render :show, status: :created, location: @box }
			else
				if @box.photo != nil
					@box.photo = nil
					@box.errors[:photo] = "Please select the image again"
				end
				format.html { render :new }
				format.json { render json: @box.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /boxes/1
	# PATCH/PUT /boxes/1.json
	def update
		entry_id = nil

		#new image
		if @box.valid? && (box_params[:photo] != nil)
			client = kaltura_setup

			#delete old entry
			if @box.photo
				if Rails.env.production?
					delete_entry(@box.photo, client)
				end
			end

			#upload new entry
			entry_id = kaltura_upload(box_params[:barcode] != nil ? box_params[:barcode] : @box.barcode,
																box_params[:photo],
																client)
		end

		#same image new barcode
		if @box.valid? && (box_params[:photo] == nil) && (box_params[:barcode] != nil)
			client = kaltura_setup

			#rename entry
			if @box.photo
				base_entry = Kaltura::KalturaBaseEntry.new
				base_entry.name = box_params[:barcode]
				base_entry_updated = client.base_entry_service.update(@box.photo, base_entry)
			end
		end

		respond_to do |format|
			if @box.update(box_params)
				if entry_id != nil
					@box.photo = entry_id
					@box.save
				end
				format.html { redirect_to @box, notice: 'Box was successfully updated.' }
				format.json { render :show, status: :ok, location: @box }
			else
				format.html { render :edit }
				format.json { render json: @box.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /boxes/1
	# DELETE /boxes/1.json
	def destroy
		@page = params[:page]

		if @box.photo
			if Rails.env.production?
				client = kaltura_setup
				delete_entry(@box.photo, client)
			end
		end

		@box.destroy
		respond_to do |format|
			format.html { redirect_to boxes_url, notice: 'Box was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	def remove_photo
		if @box.photo
			if Rails.env.production?
				client = kaltura_setup
				delete_entry(@box.photo, client)
			end

			@box.photo = nil
			@box.save
		end

		respond_to do |format|
			format.html { render :edit, notice: 'Photo was successfully removed.' }
			format.json { render :edit, status: :ok, location: @box }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_box
			@box = Box.find(params[:id])
		end

		def sort_column
			 Box.column_names.include?(params[:sort]) ? params[:sort] : "box_number"
		end

		def sort_direction
			%w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
		end
		# Never trust parameters from the scary internet, only allow the white list through.
		def box_params
			params.require(:box).permit(:barcode,:location_id, :weight, :height, :width, :depth, :box_number, :photo, {:condition_ids => []}, :description)
		end

		def logged_in_user
			unless logged_in?
				store_location
				flash[:danger] = "Please log in."
				redirect_to login_url
			end
		end

		def admin_user
			redirect_to(boxes_url) unless current_user.admin?
		end

		def kaltura_setup
			config_file = YAML.load_file("#{Rails.root}/config/kaltura.yml")

			partner_id = config_file["default"]["partner_id"]
			service_url = config_file["default"]["service_url"]
			administrator_secret = config_file["default"]["administrator_secret"]
			timeout = config_file["default"]["timeout"]

			config = Kaltura::KalturaConfiguration.new(partner_id, service_url)
			config.timeout = timeout

			client = Kaltura::KalturaClient.new( config )
			session = client.session_service.start( administrator_secret, '', Kaltura::KalturaSessionType::ADMIN )
			client.ks = session

			return client
		end

		def kaltura_upload(entry_name, photo_object, client)
			# temporal upload
			new_path = Rails.root.join('public', 'images', photo_object.original_filename)
			File.open(new_path, 'wb') do |file|
				file.write(photo_object.read)
			end

			# kaltura upload process
			media_entry = Kaltura::KalturaMediaEntry.new
			media_entry.name = entry_name
			media_entry.media_type = Kaltura::KalturaMediaType::IMAGE
			video_file = File.open(new_path)

			video_token = client.media_service.upload(video_file)
			created_entry2 = client.media_service.add_from_uploaded_file(media_entry, video_token)

			# delete temporary file
			File.delete(new_path) if File.exist?(new_path)

			return created_entry2.id
		end

		def delete_entry(entry_id, client)
			client.media_service.delete(entry_id)
		end
end

app/helpers/boxes_helper.rb
module BoxesHelper
	def box_image_for(box)
		if box.photo != nil
			entry_id = box.photo
			kaltura_url = "https://cdnapisec.kaltura.com/p/#{get_partner_id}/thumbnail/entry_id/#{entry_id}/quality/100/width/700"
			link_to( image_tag(kaltura_url, alt: box.barcode, class: "box_photo img-responsive"), "https://cdnapisec.kaltura.com/p/#{get_partner_id}/thumbnail/entry_id/#{entry_id}/quality/100/width/1000", target: "_blank" )
		end
	end

	def box_thumbnail_for(box)
		if box.photo != nil
			entry_id = box.photo
			kaltura_url = "https://cdnapisec.kaltura.com/p/#{get_partner_id}/thumbnail/entry_id/#{entry_id}/quality/100"
			link_to( image_tag(kaltura_url, alt: box.barcode, class: "box_photo img-responsive"), "https://cdnapisec.kaltura.com/p/#{get_partner_id}/thumbnail/entry_id/#{entry_id}/quality/100/width/1000", target: "_blank" )
		end
	end

	def entry_id_for(box)
		box.photo if box.photo != nil
	end

	private
		def get_partner_id
			config_file = YAML.load_file("#{Rails.root}/config/kaltura.yml")
			return partner_id = config_file["default"]["partner_id"]
		end
end

app/views/boxes/_boxes.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort]%>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= sortable "barcode" %></th>
        <th><%= sortable "box_number", "Box Number" %></th>
        <th>Thumbnail</th>
        <th><%= sortable "location_id", "Location" %></th>
        <th><%= sortable "description" %></th>
        <th><%= sortable "weight" %></th>
        <th><%= sortable "height" %></th>
        <th><%= sortable "width" %></th>
        <th><%= sortable "depth" %></th>
        <th>Condition</th>
        <th><%= sortable "updated_at", "Last updated"%></th>
        <th>Options</th>
      </tr>
    </thead>
    <tbody>
      <% @boxes.each do |box| %>
        <tr>
          <td><%= box.barcode %></td>
          <td><%= box.box_number %></td>
          <td><%= box_thumbnail_for box %></td>
          <td><% unless box.location.nil?%>
            <%= box.location.name_with_country %>
            <% end %></td>
          <td><%= box.description %></td>
          <td><%= box.weight %></td>
          <td><%= box.height %></td>
          <td><%= box.width %></td>
          <td><%= box.depth %></td>
          <td><%= box.conditions.map{ |e| e.name }.join(", ") %></td>
          <td><%= local_time_ago(box.updated_at) %></td>
          <td><%= link_to 'Show', box_path(box) %>
          <% if current_user.admin? %>
            | <%= link_to 'Items', box_items_box_path(box) %>
            | <%= link_to 'Edit', edit_box_path(box) %> |
            <%= link_to 'Delete', box, method: :delete %>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= will_paginate @boxes, renderer: BootstrapPagination::Rails %>

app/views/boxes/_form.html.erb
<%= form_for @box, html: { class: "form-horizontal"}, validate: :box_validators do |f| %>

    <div class="form-group">
      <label class="control-label">Barcode</label>
      <%= f.text_field :barcode, class: 'form-control barcode-input' %>
    </div>
    <div class="form-group">
      <label class="control-label">Box #</label>
      <%= f.text_field :box_number, class: 'form-control' %>
    </div>
    <div class="form-group">
    <label class="control-label">Location</label>
      <%= collection_select(:box, :location_id, Location.order(country: :asc), :id, :name_with_country, { prompt: "Please select a Location" }, { class: 'form-control'}) %>
    </div>
    <div class="form-group">
      <label class="control-label">Weight (lb)</label>
      <%= f.text_field :weight, class: 'form-control' %>
    </div>
    <div class="form-group">
      <label class="control-label">Height (in)</label>
      <%= f.text_field :height, class: 'form-control' %>
    </div>
    <div class="form-group">
      <label class="control-label">Width (in)</label>
      <%= f.text_field :width, class: 'form-control' %>
    </div>
    <div class="form-group">
      <label class="control-label">Depth (in)</label>
      <%= f.text_field :depth, class: 'form-control' %>
    </div>
    <div class="form-group">
      <label class="control-label">Picture</label>
      <label><%= box_image_for @box %></label>

      <% if current_user.admin? and @box.photo %>
        <%= link_to 'Remove Photo', remove_photo_box_path(@box) %>
      <% end %>

      <%= f.file_field :photo, class: 'form-control', accept: 'image/png,image/gif,image/jpeg' %>
    </div>
    <div class="form-group">
      <label class="control-label">Condition</label>
      <%= f.collection_check_boxes( :condition_ids, Condition.all, :id, :name ) do |b|%>
        <div class="row">
          <%= b.label(class: "check_box") do %>
            <div>
              <%= b.check_box(class: "check_box") %>
              <%= b.object.name %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    
    <div class="form-group">
      <label class="control-label">Description</label>
      <%= f.text_area :description, class: 'form-control' %>
    </div>

    <%= f.submit class: "btn btn-success fullwidthbutton" %>
    <%= link_to 'Back', boxes_path, class: "btn btn-warning fullwidthbutton" %>

<% end %>

app/views/boxes/box_items.erb
<% content_for :extra_js do %>
	<%= javascript_include_tag "barcode_items" %>
<% end %>
<h1 class="text-center">Box #<%= @box.box_number %> (<%= @box.barcode %>)</h1>
<h3 class="text-center info-title">Add items by scanning them or selecting them in the dropdown below</h3>
<div class="center-div box-info" data-box-number="<%= @box.box_number %>" data-id="<%= @box.id %>">
	<%= collection_select(:box, :item_ids, Item.where("box_id != ? OR box_id IS NULL", @box.id).includes(:product).order("products.name asc"), :barcode, :name_with_product ,{ :include_blank => "Select an Item" }, { class: 'form-control item-dropdown top-index-btn'}) %>
	<ul class="list-group main-list">
	<% if @items.any? %>
		<% @items.each do |item| %>
			<a href="<%= url_for(item) %>">
				<li class="list-group-item list-group-item-info" data-barcode="<%= item.barcode %>"><%= item.name_with_product %>
					<button type="button" class="close remove-item-box" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">×</span>
					</button>
				</li>
			</a>
		<% end %>	
	<% end %>
	</ul>

	<h3 class="text-center hidden not-found-title">The following scans were not found:</h3>
	<ul class="list-group not-found-list">
		
	</ul>

	<h3 class="hidden scan-title text-center">Scanned Items</h2>
	<ul class="list-group scanned-items">
		
	</ul>
		<button class="hidden loading btn fullwidthbutton btn-info"><span class="fa fa-spinner fa-spin"></span> Loading...</button>
		<a class="hidden add-scan-btn btn btn-primary fullwidthbutton"><span class="fa fa-plus"></span> Add Scanned Items</a>
		<%= link_to boxes_path, class: "btn btn-warning fullwidthbutton" do %>
			<span class="fa fa-mail-reply"></span> Back 
		<% end %>
</div>

app/views/boxes/edit.html.erb
<div class="center-div">
	<%= link_to 'Back', boxes_path, class: "btn btn-warning" %>
	<h1 class="text-center">Editing Box</h1>
	<%= render 'form' %>
	<%= yield(:box_validators) %>
</div>

app/views/boxes/index.html.erb
<h1 class="text-center">Boxes</h1>

<%= search_form_for @q, url: boxes_path(page: 1), html: { method: :get, class: "form-inline form-main-search", id: "ajax_search" } do |f| %>
	<div class="form-group">
		<%= f.search_field :barcode_or_description_or_location_name_or_location_country_cont, class: "form-control" %>
		<%= f.submit "Search", :name => nil, class: "btn btn-primary" %>
	</div>
	<% if current_user.admin? %>
	  <%= link_to "Add Box", new_box_path , class: "btn btn-success top-index-btn" %>
	<% end %>
	<div id="ajax_objects" ><%= render 'boxes' %></div>
<% end %>
<% if current_user.admin? %>
  <%= link_to "Add Box", new_box_path , class: "btn btn-success" %>
<% end %>

app/views/boxes/index.js.erb
$("#ajax_objects").html("<%= escape_javascript(render('boxes'))%>");

app/views/boxes/new.html.erb
<div class="center-div">
  <%= link_to 'Back', boxes_path, class: "btn btn-warning" %>
  <h1 class="text-center">New Box</h1>
  <%= render 'form' %>
  <%= yield(:box_validators) %>
</div>

app/views/boxes/show.html.erb
<h1 class="text-center">Box #<%= @box.box_number %> (<%= @box.barcode %>)</h1>
<div class="center-div">
	<div class="thumbnail">
		<%= box_image_for @box %>
		</br>
        <div class="caption-full">
	        <% unless @box.height.nil? && @box.width.nil? && @box.depth.nil? %>
	        	<h4 class="pull-right"><%= @box.height %> x <%= @box.width %> x <%= @box.depth %></h4>
	        <% end %>
	        <% unless @box.location.nil? %>
	        	<p><b>Location:</b> <%= @box.location.name_with_country %></p>
	        <% end %>
	        <% unless @box.weight.nil? %>
	        	<p><b>Weight:</b> <%= @box.weight %> lbs</p>
	        <% end %>
	        <% unless @box.conditions.empty? %>
	        	<p><b>Condition:</b> <%= @box.conditions.map{ |e| e.name }.join(", ") %></p>
	        <% end %>
	        <% unless @box.description.nil? %>
	        	<p><b>Description:</b> <%= @box.description %></p>
	        <% end %>
	        <p><b>Creation date:</b> <%= local_time(@box.created_at) %></p>
        </div>
	</div>
    <%= link_to "Go to Items", box_items_box_path(@box), class: "btn btn-info fullwidthbutton" %>

	<% if current_user.admin? %>
		<%= link_to 'Edit', edit_box_path(@box) , class: "btn btn-warning fullwidthbutton" %>
	<% end %>
	<%= link_to 'Back', boxes_path, class: "btn btn-default fullwidthbutton" %>
</div>