config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :boxes do
    member do
      get 'box_items'
      post 'add_scans'
      post 'remove_item'
    end
  end

  get 'boxes/:id/remove_photo', to: 'boxes#remove_photo', as: 'remove_photo_box'
  get 'items/:id/remove_photo', to: 'items#remove_photo', as: 'remove_photo_item'

  get 'items/item_dropdown', to: 'items#item_dropdown', as: 'item_dropdown'
  get 'movements/box_dropdown', to: "movements#box_dropdown", as: "box_dropdown"
  get "university_contacts/contact_dropdown", to: "university_contacts#contact_dropdown", as: "contact_dropdown"
  get "embed_code_universities/university_dropdown", to: "embed_code_universities#university_dropdown", as: "university_dropdown"

  get 'university_contacts/:contact_id/embed_code_universities', to: 'university_contacts#embed_code_universities'
  get 'embed_code_universities/:university_id/university_contacts', to: 'embed_code_universities#university_contacts'

  post 'embed_code_universities/add_contact', to: 'embed_code_universities#add_contact'
  post 'university_contacts/add_university', to: 'university_contacts#add_university'

  post 'embed_code_universities/:contact_id/remove_contact', to: 'embed_code_universities#remove_contact'
  post 'university_contacts/:university_id/remove_university', to: 'university_contacts#remove_university'

  get 'embed_code_universities/new/:contact_id', to: 'embed_code_universities#new'
  get 'university_contacts/new/:university_id', to: 'university_contacts#new'

  delete 'events/remove_university_from_event', to: 'events#remove_university_from_event', as: 'remove_university_from_event'

  get 'events/generate_code', to: 'events#generate_code', as: 'generate_code'
  get 'events/show_code', to: "events#show_code", as: 'show_code'
  get 'embed_codes/:id/get_variables', to: "embed_codes#get_variables", as: 'get_variables'
  post 'events/:events_university_id/add_code', to: "events#add_code", as: "add_code"
  get 'events/edit_event_university', to: "events#edit_event_university", as: "edit_event_university"
  patch 'events/update_events_university', to: "events#update_event_university", as: "update_events_university"

  resources :movements do
    member do
      get 'movement_boxes'
      get 'return'
      post 'add_scans'
      post 'remove_box'
    end
  end
  resources :embed_codes, :embed_code_variables, :events, :software_serials, :softwares, :categories, :products, :items, :users, :locations, :conditions, :university_contacts, :embed_code_universities
  resources :password_resets, only: [:new, :create, :edit, :update]
  # get 'boxes/add_item/:id', to: 'boxes#add_item', as: 'add_item'

  get 'reports', to: 'reports#index', as: 'reports_index'
  get 'reports/boxes_per_movement', to: 'reports#boxes_per_movement_index', as: 'boxes_per_movement_index'
  get 'reports/boxes_per_movement/:id', to: 'reports#boxes_per_movement', as: 'boxes_per_movement'
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :events_universities
  has_many :embed_code_universities, -> { select 'embed_code_universities.*, events_universities.comments as event_comments, events_universities.status as event_status'}, through: :events_universities
  validates :short_url, format: { without: /\s/ }
  accepts_nested_attributes_for :events_universities

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user
  before_action :admin_user, only: [:new, :create, :edit, :update, :destroy]
  helper_method :sort_column
  # GET /events
  # GET /events.json
  def index
		sc = sort_column
		@q = Event.ransack(params[:q])
		@sort = sc + " "
		if params[:page]
			cookies[:events_page] = {
				value: params[:page],
				expires: 1.day.from_now
			}
		end
		@events = @q.result.order(@sort + sort_direction).page(cookies[:events_page]).per_page(20)
	end

  # GET /events/1
  # GET /events/1.json
  def show
    sc = sort_column
    @sort = sc + " "
    if params[:page]
			cookies[:event_universities_page] = {
				value: params[:page],
				expires: 1.day.from_now
			}
		end
    @embed_code_universities = @event.embed_code_universities.order(@sort + sort_direction).page(cookies[:event_universities_page])
    @events_universities = @event.events_universities
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  def add_code
    @events_university = EventsUniversity.find(params[:events_university_id])
    @code = params[:embed_code]
    @events_university.code = @code
    puts @code
    respond_to do |format|
      if @events_university.save
        format.json { render json: @events_university }
      else
        format.json { render json: @events_university.errors, status: :unprocessable_entity }
      end
    end
  end
  # GET /events/1/edit
  def edit
  end

  def edit_event_university
    @university = EmbedCodeUniversity.find(params[:university_id])
    @event = Event.find(params[:event_id])
    @events_university = EventsUniversity.includes(:event, :embed_code_university).where(event_id: @event.id, embed_code_university_id: @university.id).take
  end

  def update_event_university
    @events_university = EventsUniversity.find(params[:events_university_id])
    @embed_code_university = @events_university.embed_code_university
    respond_to do |format|
      if @events_university.update(params[:events_university].require("events_university").permit(:comments, :status)) && @embed_code_university.update(params[:events_university].require("embed_code_university").permit(:acronym, :name, :test_site, :test_user, :test_password))
        format.html { redirect_to @events_university.event, notice: 'University was successfully updated.' }
      else
        format.html { render :edit_event_university }
      end
    end
#     {"utf8"=>"✓", "_method"=>"patch", "authenticity_token"=>"K8txCOzLW7W73tShIfPFZibJcGWcIsgCslP7jtKiD7KmjILeV2W7vwlHglJcILE
# d52mr8y2nMMMIY7eGq6OHlg==", "events_university"=>{"embed_code_university"=>{"acronym"=>"FG", "name"=>"FG", "test_site"=>
# "", "test_user"=>"", "test_password"=>""}, "events_university"=>{"comments"=>"hola", "status"=>"adios"}}, "events_univer
# sity_id"=>"23", "commit"=>"Update Events university", "controller"=>"events", "action"=>"update_event_university"}
    # respond_to do |format|
    #   if @event.update(event_params)
    #     format.html { redirect_to events_url, notice: 'Event was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @event }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @event.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def generate_code
    @university = EmbedCodeUniversity.find(params[:university_id])
    @event = Event.find(params[:event_id])
    @events_university = EventsUniversity.where(event_id: @event.id, embed_code_university_id: @university.id).take
    @embed_codes = EmbedCode.all
    #@embed_code = EmbedCode.where(events_university_id: @events_university.id)
    #if @embed_code.empty?
    #  @embed_code = EmbedCode.new(events_university_id: @events_university.id)
    #end
    #@embed_code.save
  end

  def show_code
    @university = EmbedCodeUniversity.find(params[:university_id])
    @event = Event.find(params[:event_id])
    @events_university = EventsUniversity.where(event_id: @event.id, embed_code_university_id: @university.id).take

  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        @universities_ids = EmbedCodeUniversity.all.ids
        events_universities = []
        @universities_ids.each do |university_id|
          events_universities << EventsUniversity.new(:event_id => @event.id, :embed_code_university_id => university_id)
        end
        EventsUniversity.import events_universities
        format.html { redirect_to events_url, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to events_url, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_university_from_event
    @event_university = EventsUniversity.where(embed_code_university_id: params[:university_id], event_id: params[:event_id])
    @event = Event.find(params[:event_id])
    @event.events_universities.destroy(@event_university)
    respond_to do |format|
      format.html { redirect_to @event, notice: 'University was removed from Event.' }
      format.json { render json: @event}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def sort_direction
			%w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
		end

    def sort_column
      Event.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :short_url, :embed_code, :acronym, :comments, :status, :test_site, :test_user, :test_password)
    end

    def logged_in_user
			unless logged_in?
				store_location
				flash[:danger] = "Please log in."
				redirect_to login_url
			end
		end

		def admin_user
			redirect_to(products_url) unless current_user.admin?
		end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_universities.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort]%>
<div class="table-responsive">
  <table class="table table-striped table-hover">
	<thead>
	  <tr>
  		<th><%= sortable "acronym" %></th>
  		<th><%= sortable "name" %></th>
  		<th><%= sortable "event_comments" %></th>
  		<th><%= sortable "event_status" %></th>
  		<th>Options</th>
	  </tr>
	</thead>
	<tbody>
	  <% @embed_code_universities.each do |university| %>
		<tr data-toggle="modal"  data-acronym="<%= university.acronym %>" data-target="#contacts-modal" data-id="<%= university.id %>">
		  <td class="hover-me"><%= university.acronym %></td>
		  <td class="hover-me"><%= university.name %></td>
		  <td class="hover-me"><%= university.event_comments %></td>
		  <td class="hover-me"><%= university.event_status %></td>
		  <td>
        <% if @events_universities.where(embed_code_university_id: university.id, event_id: @event.id).take.code.blank? %>
          <%= link_to 'Generate Code', generate_code_path(event_id: @event.id, university_id: university.id), method: :get %>
        <% else %>
          <%= link_to "Show Code", show_code_path(event_id: @event.id, university_id: university.id), method: :get %>
        <% end %> |
		  <% if current_user.admin? %>
			  <%= link_to 'Edit', edit_event_university_path(event_id: @event.id, university_id: university.id), method: :get %> |
          <%= link_to 'Remove from Event', remove_university_from_event_path(event_id: @event.id,university_id: university.id), method: :delete %>
		  <% end %>
		  </td>
		</tr>
	  <% end %>
	</tbody>
  </table>
</div>
<%= will_paginate @embed_code_universities, renderer: BootstrapPagination::Rails %>
<div class="modal fade" id="contacts-modal" tabindex="-1" role="dialog" aria-labelledby="gridUniversityContactModal">
 	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
				<h3>University Contacts</h3>
				<div class="content-loader loader--wide">
				  <span class="dot"></span>
				  <span class="dot"></span>
				  <span class="dot"></span>
				</div>
			</div>
			<div class="modal-body hidden">
				<h4>University contacts for: <span class="modal-acronym"></span></h4>
				<div class="table-responsive">
					<table class="table table-striped" id="tblGrid" >
						<thead id="tblHead">
							<tr>
								<th>Name</th>
								<th>Email</th>
								<th>Skype</th>
								<th class="text-right">Role</th>
							</tr>
						</thead>
						<tbody class="university-contacts-list">

						</tbody>
					</table>
				</div>
			</div>
			<div class="modal-footer hidden">
  				<%= link_to 'Create New Contact', new_university_contact_path, class: "btn btn-success new-contact-btn" %>
  				<a class="btn btn-success add-contact-btn">Add Existing Contact</a>
  				<button type="button" data-dismiss="modal" class="btn" >Close</button>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="add-contacts-modal" tabindex="-1" >
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
					<h3>University Contacts</h3>
					<div class="content-loader loader--wide">
					  <span class="dot"></span>
					  <span class="dot"></span>
					  <span class="dot"></span>
					</div>

			</div>
			<div class="modal-body hidden">
        <div class="alert alert-danger hidden">
          <span class="fa fa-exclamation" role="alert"></span>
          <span class="sr-only">Error: </span>
          You must select a contact in the dropdown list.
        </div>

        <h4>Select the contact you would like to add for <span class="modal-acronym"></span></h4>
				<select class="form-control contact-dropdown"></select>

			</div>
			<div class="modal-footer hidden">
        <button type="button" class="btn btn-primary add-contact">Add</button>
        <button type="button" class="btn" data-dismiss="modal" >Close</button>
			</div>
		</div>
	</div>
</div>

app/views/events/_event_university_form.html.erb
<%= form_for @events_university, url: update_events_university_path, html: { class: "form-horizontal"}, validate: :events_university_validators do |f| %>
  <%= f.fields_for @events_university.embed_code_university, html: { class: "form-horizontal"} do |ff| %>
    <div class="form-group">
      <label class="control-label">Acronym</label>
      <%= ff.text_field :acronym, class: 'form-control' %>
    </div>
    <div class="form-group">
      <label class="control-label">Name</label>
      <%= ff.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <label class="control-label">Test Site</label>
      <%= ff.text_field :test_site, class: 'form-control' %>
    </div>

    <div class="form-group">
      <label class="control-label">Test User</label><br>
      <%= ff.text_field :test_user, class: 'form-control' %>
    </div>
    <div class="form-group">
      <label class="control-label">Test Password</label>
      <%= ff.text_field :test_password, class: 'form-control' %>
    </div>
  <% end %>
  <%= f.fields_for @events_university, html: { class: "form-horizontal"} do |ff| %>
  <div class="form-group">
    <label class="control-label">Comments</label>
    <%= ff.text_area :comments, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label class="control-label">Status</label>
    <%= ff.text_field :status, class: 'form-control' %>
  </div>
  <% end %>
  <%= hidden_field_tag 'events_university_id', @events_university.id %>

  <%= f.submit class: "btn btn-success fullwidthbutton" %>
  <%= link_to "Back", @events_university.event, class: "btn btn-warning fullwidthbutton" %>
<% end %>

app/views/events/_events.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort]%>
<div class="table-responsive">
  <table class="table table-striped table-hover">
	<thead>
	  <tr>
		<th><%= sortable "name" %></th>
    <th><%= sortable "short_url" %></th>
		<th>Options</th>
	  </tr>
	</thead>

	<tbody>
	  <% @events.each do |event| %>
		<tr>
		  <td><%= event.name %></td>
		  <td><%= event.short_url %></td>
		  <td><%= link_to 'Universities', event %> |
		  <% if current_user.admin? %>
			<%= link_to 'Edit', edit_event_path(event) %> |
			<%= link_to 'Delete', event, method: :delete %>
		  <% end %>
		  </td>
		</tr>
	  <% end %>
	</tbody>
  </table>
</div>
<%= will_paginate @events, renderer: BootstrapPagination::Rails %>

app/views/events/_form.html.erb
<%= form_for @event, html: { class: "form-horizontal"}, validate: :event_validators do |f| %>
  <div class="form-group">
    <label class="control-label">Name</label>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label class="control-label">Short Url</label>
    <%= f.text_field :short_url, class: 'form-control' %>
  </div>
  <%= f.submit class: "btn btn-success fullwidthbutton" %>
  <%= link_to "Back", events_path, class: "btn btn-warning fullwidthbutton" %>
<% end %>

app/views/events/edit.html.erb
<div class="center-div">
	<%= link_to 'Back', events_path, class: "btn btn-warning" %>
	<h1 class="text-center">Editing Live Event</h1>
	<%= render 'form' %>
	<%= yield(:event_validators) %>
</div>

app/views/events/edit_event_university.html.erb
<div class="center-div">
	<%= link_to 'Back', @events_university.event, class: "btn btn-warning" %>
	<h1 class="text-center">Editing Event University</h1>
	<%= render 'event_university_form' %>
	<%= yield(:events_university_validators) %>
</div>

app/views/events/generate_code.html.erb
<h1 class="text-center">Generate code for <%= @university.acronym %> at <%= @event.name %></h1>

<h3 class="text-center info-title">Select an embed code template</h3>
<div class="center-div" data-university-id="<%= @university.id %>" data-event-id="<%= @event.id %>" data-events-university-id="<%= @events_university.id %>">
  <div class="alert alert-success alert-dismissible" style="display:none;" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <strong>Embed Code for <%= @university.name %> has been successfully created!</strong> Click <a target="_blank" download="<%= @event.short_url%> - <%= @university.acronym %>.txt" class="download-code-link" href="">Download</a> to download the code.
  </div>
  <%= collection_select(:events_university, :id, EmbedCode.all, :id, :name ,{ include_blank: "Select a Template", selected: "" }, { class: 'form-control templates-dropdown top-index-btn'}) %>


</div>
<% @embed_codes.each do |embed_code| %>
  <pre name="code" data-embed-code-id="<%= embed_code.id %>" class="embed_<%= embed_code.id %> highlighter " style="display:none;" >
    <%= embed_code.code %>
  </pre>
<% end %>
<div class="center-div">
  <a class="btn btn-primary fullwidthbutton generate-button" data-toggle="modal" data-target="#variables-modal" style="display:none;"><span class="fa fa-plus"></span> Generate Embed Code</a>
  <a href="" target="_blank" download="<%= @event.short_url%> - <%= @university.acronym %>.txt" class="btn fullwidthbutton top-index-btn btn-warning download-code-link" style="display:none;"type="hidden"><span class="fa fa-download"></span> Download</a>

</div>


<!-- EMBED CODE VARIABLES MODAL -->

<div class="modal fade" id="variables-modal" tabindex="-1" role="dialog" aria-labelledby="gridVariablesModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
        <h3>Embed Code Variables</h3>
        <div class="content-loader loader--wide">
          <span class="dot"></span>
          <span class="dot"></span>
          <span class="dot"></span>
        </div>
    </div>
    <div class="modal-body hidden">
      <div class="form-group">

      </div>
          <a class="btn btn-success generate-code">Generate Code</a>
        <button type="button" data-dismiss="modal" class="btn" >Close</button>

    </div>
  </div>
  </div>
</div>

app/views/events/index.html.erb
<h1 class="text-center">Live Events</h1>

<%= search_form_for @q, url: events_path(page: 1), html: { method: :get, class: "form-inline form-main-search", id: "ajax_search"} do |f| %>
	<div class="form-group">
		<%= f.search_field :short_url_or_name_cont, class: "form-control" %>
		<%= f.submit "Search", :name => nil, class: "incread-width btn btn-primary"%>
	</div>
	<% if current_user.admin? %>
		<%= link_to 'Add Event', new_event_path, class: "top-index-btn btn btn-success" %>
			<% end %>
  	<div id="ajax_objects" ><%= render 'events' %></div>
<% end %>
<% if current_user.admin? %>
  <%= link_to 'Add Event', new_event_path, class: "btn btn-success" %>
<% end %>

app/views/events/new.html.erb
<div class="center-div">
	<%= link_to 'Back', events_path, class: "btn btn-warning" %>
	<h1 class="text-center">New Live Event</h1>
	<%= render 'form' %>
  <%= yield(:event_validators) %>
</div>

app/views/events/show.html.erb
<h1 class="text-center">Universities for <%= @event.name %></h1>

<div id="ajax_objects" ><%= render 'event_universities' %></div>

app/views/events/show_code.html.erb
<h1 class="text-center">Embeded Code for <%= @university.acronym %> at <%= @event.name %></h1>

<h3 class="text-center info-title">Click in the download button to get the code in a .txt file</h3>
<pre name="code" class="highlighter " >
  <%= @events_university.code %>
</pre>
<div class="center-div">
  <a href="" target="_blank" download="<%= @event.short_url%> - <%= @university.acronym %>.txt" class="btn fullwidthbutton top-index-btn btn-success trigger-code show-code-link" type="hidden"><span class="fa fa-download"></span> Download</a>
  <%= link_to 'Back', @event, class: "btn btn-warning fullwidthbutton" %>
</div>