config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :boxes do
    member do
      get 'box_items'
      post 'add_scans'
      post 'remove_item'
    end
  end

  get 'boxes/:id/remove_photo', to: 'boxes#remove_photo', as: 'remove_photo_box'
  get 'items/:id/remove_photo', to: 'items#remove_photo', as: 'remove_photo_item'

  get 'items/item_dropdown', to: 'items#item_dropdown', as: 'item_dropdown'
  get 'movements/box_dropdown', to: "movements#box_dropdown", as: "box_dropdown"
  get "university_contacts/contact_dropdown", to: "university_contacts#contact_dropdown", as: "contact_dropdown"
  get "embed_code_universities/university_dropdown", to: "embed_code_universities#university_dropdown", as: "university_dropdown"

  get 'university_contacts/:contact_id/embed_code_universities', to: 'university_contacts#embed_code_universities'
  get 'embed_code_universities/:university_id/university_contacts', to: 'embed_code_universities#university_contacts'

  post 'embed_code_universities/add_contact', to: 'embed_code_universities#add_contact'
  post 'university_contacts/add_university', to: 'university_contacts#add_university'

  post 'embed_code_universities/:contact_id/remove_contact', to: 'embed_code_universities#remove_contact'
  post 'university_contacts/:university_id/remove_university', to: 'university_contacts#remove_university'

  get 'embed_code_universities/new/:contact_id', to: 'embed_code_universities#new'
  get 'university_contacts/new/:university_id', to: 'university_contacts#new'

  delete 'events/remove_university_from_event', to: 'events#remove_university_from_event', as: 'remove_university_from_event'

  get 'events/generate_code', to: 'events#generate_code', as: 'generate_code'
  get 'events/show_code', to: "events#show_code", as: 'show_code'
  get 'embed_codes/:id/get_variables', to: "embed_codes#get_variables", as: 'get_variables'
  post 'events/:events_university_id/add_code', to: "events#add_code", as: "add_code"
  get 'events/edit_event_university', to: "events#edit_event_university", as: "edit_event_university"
  patch 'events/update_events_university', to: "events#update_event_university", as: "update_events_university"

  resources :movements do
    member do
      get 'movement_boxes'
      get 'return'
      post 'add_scans'
      post 'remove_box'
    end
  end
  resources :embed_codes, :embed_code_variables, :events, :software_serials, :softwares, :categories, :products, :items, :users, :locations, :conditions, :university_contacts, :embed_code_universities
  resources :password_resets, only: [:new, :create, :edit, :update]
  # get 'boxes/add_item/:id', to: 'boxes#add_item', as: 'add_item'

  get 'reports', to: 'reports#index', as: 'reports_index'
  get 'reports/boxes_per_movement', to: 'reports#boxes_per_movement_index', as: 'boxes_per_movement_index'
  get 'reports/boxes_per_movement/:id', to: 'reports#boxes_per_movement', as: 'boxes_per_movement'
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_paper_trail


	belongs_to :product
	belongs_to :box
	belongs_to :location
	has_many :software_serials
	validates_uniqueness_of :barcode, case_sensitive: false
	validates :price, numericality: { allow_blank: true }
	validates :barcode, :product_id, presence: true
	has_and_belongs_to_many :conditions
	def name_with_product
		@product_name = self.product.name_with_brand
		"#{@product_name} (#{barcode})"
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user, only: [:new, :create, :edit, :update, :destroy, :remove_photo]
  before_action :set_item, only: [:show, :edit, :update, :destroy, :remove_photo]
  helper_method :sort_column
  # GET /items
  # GET /items.json
  def index
    sc = sort_column
    @q = Item.ransack(params[:q])
    @sort = sc
    if sc.eql? "box_id"
      @sort = "boxes.box_number"
    elsif sc.eql? "product_id"
      @sort = "products.name"
    elsif sc.eql? "location_id"
      @sort = "locations.country"
    elsif sc.eql? "category_id"
      @sort = "categories.name"
    end
    if params[:page]
      cookies[:items_page] = {
        value: params[:page],
        expires: 1.day.from_now
      }
    end
    @items = @q.result.includes(:box, :location, {:product => [:category]}).order(@sort + " " + sort_direction).page(cookies[:items_page]).per_page(10)

  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    if @item.valid? && @item.photo?
      client = kaltura_setup
      entry_id = kaltura_upload(item_params[:barcode], item_params[:photo], client)
      @item.photo = entry_id
    end

    respond_to do |format|
      if @item.save
        format.html { redirect_to items_url, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        if @item.photo != nil
          @item.photo = nil
          @item.errors[:photo] = "Please select the image again"
        end
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    entry_id = nil

    #new image
    if @item.valid? && (item_params[:photo] != nil)
      client = kaltura_setup

      #delete old entry
      if @item.photo and Rails.env.production?
        delete_entry(@item.photo, client)
      end

      #upload new entry
      entry_id = kaltura_upload(item_params[:barcode] != nil ? item_params[:barcode] : @item.barcode,
                                item_params[:photo],
                                client)
    end

    #same image new barcode
    if @item.valid? && (item_params[:photo] == nil) && (item_params[:barcode] != nil)
      client = kaltura_setup

      if @item.photo
        #rename entry
        base_entry = Kaltura::KalturaBaseEntry.new
        base_entry.name = item_params[:barcode]
        base_entry_updated = client.base_entry_service.update(@item.photo, base_entry)
      end
    end

    respond_to do |format|
      if @item.update(item_params)
        if entry_id != nil
          @item.photo = entry_id
          @item.save
        end

        format.html { redirect_to items_url, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    if @item.photo and Rails.env.production?
      client = kaltura_setup
      delete_entry(@item.photo, client)
    end

    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_photo
    if @item.photo
      if Rails.env.production?
        client = kaltura_setup
        delete_entry(@item.photo, client)
      end

      @item.photo = nil
      @item.save
    end

    respond_to do |format|
      format.html { render :edit, notice: 'Photo was successfully removed.' }
      format.json { render :edit, status: :ok, location: @item }
    end
  end

  def item_dropdown
    @box_id = params.require(:box_id)
    @items = Item.includes(:product).where("box_id != ? OR box_id IS NULL", @box_id).order("products.name asc").map { |i| [i.barcode, i.product.name, i.product.brand ]}
    respond_to do |format|
      format.json { render json: [{ items: @items }]}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def sort_column
      if params[:sort].eql? "category_id"
        "category_id"
      else
        Item.column_names.include?(params[:sort]) ? params[:sort] : "barcode"
      end
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:barcode,:location_id ,:box_id, :product_id, :category_id, :serial_number, :model_number, :price, {:condition_ids => []}, :firmware, :photo, :responsable, :notes)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def admin_user
      redirect_to(items_url) unless current_user.admin?
    end

    def kaltura_setup
      config_file = YAML.load_file("#{Rails.root}/config/kaltura.yml")

      partner_id = config_file["default"]["partner_id"]
      service_url = config_file["default"]["service_url"]
      administrator_secret = config_file["default"]["administrator_secret"]
      timeout = config_file["default"]["timeout"]

      config = Kaltura::KalturaConfiguration.new(partner_id, service_url)
      config.timeout = timeout

      client = Kaltura::KalturaClient.new( config )
      session = client.session_service.start( administrator_secret, '', Kaltura::KalturaSessionType::ADMIN )
      client.ks = session

      return client
    end

    def kaltura_upload(entry_name, photo_object, client)
      # temporal upload
      new_path = Rails.root.join('public', 'images', photo_object.original_filename)
      File.open(new_path, 'wb') do |file|
        file.write(photo_object.read)
      end

      # kaltura upload process
      media_entry = Kaltura::KalturaMediaEntry.new
      media_entry.name = entry_name
      media_entry.media_type = Kaltura::KalturaMediaType::IMAGE
      video_file = File.open(new_path)

      video_token = client.media_service.upload(video_file)
      created_entry2 = client.media_service.add_from_uploaded_file(media_entry, video_token)

      # delete temporary file
      File.delete(new_path) if File.exist?(new_path)

      return created_entry2.id
    end

    def delete_entry(entry_id, client)
      client.media_service.delete(entry_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
	def image_for(item)
		if item.photo != nil
			entry_id = item.photo
			kaltura_url = "http://cdnapisec.kaltura.com/p/#{get_partnet_id}/thumbnail/entry_id/#{entry_id}/quality/100/width/200"
			image_tag(kaltura_url, alt: item.product.name, class: "item_photo")
		end
	end

	def entry_id_for(item)
		item.photo if item.photo != nil
	end

	private
		def get_partnet_id
			config_file = YAML.load_file("#{Rails.root}/config/kaltura.yml")
			return partner_id = config_file["default"]["partner_id"]
		end
end

app/views/items/_form.html.erb
<%= form_for @item, html: { class: "form-horizontal"}, validate: :item_validators do |f| %>
  <div class="form-group">
    <label class="control-label">Barcode</label>
    <%= f.text_field :barcode, class: 'form-control barcode-input' %>
  </div>
  <div class="form-group">
    <label class="control-label">Product</label>
    <%= collection_select(:item, :product_id, Product.order(name: :asc), :id, :name_with_brand, { prompt: "Please select a Product"},{ class: 'form-control'} ) %>
  </div>
  <div class="form-group">
    <label class="control-label">Box</label>
    <%= collection_select(:item, :box_id, Box.order(box_number: :asc), :id, :box_number_with_barcode, { prompt: "Please select a Box" }, { class: 'form-control'}) %>
  </div>
  <div class="form-group">
    <label class="control-label">Location</label>
    <%= collection_select(:item, :location_id, Location.order(country: :asc), :id, :name_with_country, { prompt: "Please select a Location" }, { class: 'form-control'}) %>
  </div>
  <div class="form-group">
    <label class="control-label">Condition</label>
    <%= f.collection_check_boxes( :condition_ids, Condition.all, :id, :name ) do |b|%>
      <div class="row">
        <%= b.label(class: "check_box") do %>
          <div>
            <%= b.check_box(class: "check_box") %>
            <%= b.object.name %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="form-group">
    <label class="control-label">Serial Number</label>
    <%= f.text_field :serial_number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label class="control-label">Model Number</label>
    <%= f.text_field :model_number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label class="control-label">Price $ </label>
    <%= f.text_field :price, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label class="control-label">Firmware</label>
    <%= f.text_field :firmware, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label class="control-label">Picture</label><br>
    <label><%= image_for @item %></label>

    <% if current_user.admin? and @item.photo %>
      <%= link_to 'Remove Photo', remove_photo_item_path(@item) %>
    <% end %>

    <%= f.file_field :photo, class: 'form-control', accept: 'image/png,image/gif,image/jpeg' %>
  </div>
  <div class="form-group">
    <label class="control-label">Additional Notes</label>
    <%= f.text_area :notes, class: 'form-control' %>
  </div>

  <%= f.submit class: "btn btn-success fullwidthbutton" %>
  <%= link_to "Back", items_path, class: "btn btn-warning fullwidthbutton" %>
<% end %>

app/views/items/_items.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort]%>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= sortable "barcode" %></th>
        <th><%= sortable "product_id", "Product" %></th>
        <th><%= sortable "box_id", "Box"%></th>
        <th><%= sortable "category_id", "Category" %></th>
        <th><%= sortable "location_id", "Location" %></th>
        <th><%= sortable "serial_number" %></th>
        <th><%= sortable "model_number" %></th>
        <th><%= sortable "firmware" %></th>
        <th>Condition</th>
        <th><%= sortable "created_at", "Creation date" %></th>
        <th><%= sortable "updated_at", "Last updated"%></th>
        <th>Options</th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.barcode %></td>
          <td><%= item.product.name_with_brand %></td>
          <td><% unless item.box.nil? %>
            <%= item.box.box_number %>
          <% end %></td>
          <td><% unless item.product.category.nil? %>
            <%= item.product.category.name %>
          <% end %></td>
          <td><% unless item.location.nil? %>
            <%= item.location.name_with_country %>
            <% end %></td>
          <td><%= item.serial_number %></td>
          <td><%= item.model_number %></td>
          <td><%= item.firmware %></td>
          <td>
            <%= item.conditions.map{ |e| e.name}.join(",") %>
          </td>
          <td><%= local_time_ago(item.created_at) %></td>
          <td><%= local_time_ago(item.updated_at) %></td>
          <td><%= link_to 'Show', item %> |
          <% if current_user.admin? %>
            <%= link_to 'Edit', edit_item_path(item) %> |
            <%= link_to 'Delete', item, method: :delete %>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= will_paginate @items, renderer: BootstrapPagination::Rails %>

app/views/items/edit.html.erb
<div class="center-div">
	<%= link_to 'Back', items_path, class: "btn btn-warning" %>
	<h1 class="text-center">Editing Item</h1>
	<%= render 'form' %>
	<%= yield(:item_validators) %>
</div>

app/views/items/index.html.erb
<h1 class="text-center">Items</h1>

<%= search_form_for @q, url: items_path(page: 1), html: { method: :get, class: "form-inline form-main-search", id: "ajax_search"} do |f| %>
	<div class="form-group">
		<%= f.search_field :barcode_or_product_name_or_product_brand_or_product_category_name_or_location_name_or_location_country_cont, class: "form-control" %>
		<%= f.submit "Search", :name => nil, class: "incread-width btn btn-primary"%>
	</div>
	<% if current_user.admin? %>
		<%= link_to 'Add Item', new_item_path, class: "top-index-btn btn btn-success" %>
	<% end %>
  	<div id="ajax_objects" ><%= render 'items' %></div>
<% end %>
<% if current_user.admin? %>
  <%= link_to 'Add Item', new_item_path, class: "btn btn-success" %>
<% end %>

app/views/items/index.js.erb
$("#ajax_objects").html("<%= escape_javascript(render('items'))%>")

app/views/items/new.html.erb
<div class="center-div">
	<%= link_to 'Back', items_path, class: "btn btn-warning" %>
	<h1 class="text-center">New Item</h1>
	<%= render 'form' %>
	<%= yield(:item_validators) %>
</div>

app/views/items/show.html.erb
<div class="center-div">
	<div class="thumbnail">
		<%= image_for @item %>
        <div class="caption-full">
	        <h3><%= @item.barcode %></h3>

	        <h4><% unless @item.box.nil? %>
				Box #<%= @item.box.box_number %> (<%= @item.box.barcode %>)
			<% end %></h4>

	        <% unless @item.product.nil? %>
		        <p>
					<strong>Product:</strong>
					<%= @item.product.name_with_brand %>
				</p>
			<% end %>
			<% unless @item.location.nil?  %>
				<p>
					<strong>Location:</strong>
					<%= @item.location.name_with_country %>
				</p>
			<% end %>


			<% unless @item.serial_number.nil? %>
				<p>
					<strong>Serial Number:</strong>
					<%= @item.serial_number%>
				</p>
			<% end %>

			<% unless @item.model_number.nil? %>
				<p>
					<strong>Model Number:</strong>
					<%= @item.model_number %>
				</p>
			<% end %>

			<% unless @item.price.nil? %>
				<p>
					<strong>Price:</strong>
					<%= @item.price %>
				</p>
			<% end %>

			<% unless @item.conditions.empty? %>
				<p>
					<strong>Condition:</strong> <%= @item.conditions.map{ |e| e.name }.join(", ") %>
				</p>
			<% end %>


			<% unless @item.firmware.nil?%>
				<p>
					<strong>Firmware:</strong>
					<%= @item.firmware%>
				</p>
			<% end %>

			<% unless @item.responsable.nil? %>
				<p>
					<strong>Responsable:</strong>
					<%= @item.responsable %>
				</p>
			<% end %>

			<% if @item.notes.present? %>
				<p>
					<strong>Additional notes:</strong>
					<%= @item.notes %>
				</p>
			<% end %>
        </div>
    </div>

	<% if current_user.admin? %>
		<%= link_to 'Edit', edit_item_path(@item) , class: "btn btn-warning" %> |
	<% end %>
	<%= link_to 'Back', :back %>
</div>